config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"
  resources :student_cohorts
  resources :teacher_cohorts
  resources :teachers_cohorts
  resources :teachers
  resources :students
  resources :cohorts
  resources :courses
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher_cohort.rb
class TeacherCohort < ApplicationRecord
end

app/controllers/teacher_cohorts_controller.rb
class TeacherCohortsController < ApplicationController
  before_action :set_teacher_cohort, only: [:show, :edit, :update, :destroy]

  # GET /teacher_cohorts
  # GET /teacher_cohorts.json
  def index
    @teacher_cohorts = TeacherCohort.all
  end

  # GET /teacher_cohorts/1
  # GET /teacher_cohorts/1.json
  def show
  end

  # GET /teacher_cohorts/new
  def new
    @teacher_cohort = TeacherCohort.new
  end

  # GET /teacher_cohorts/1/edit
  def edit
  end

  # POST /teacher_cohorts
  # POST /teacher_cohorts.json
  def create
    @teacher_cohort = TeacherCohort.new(teacher_cohort_params)

    respond_to do |format|
      if @teacher_cohort.save
        format.html { redirect_to @teacher_cohort, notice: 'Teacher cohort was successfully created.' }
        format.json { render :show, status: :created, location: @teacher_cohort }
      else
        format.html { render :new }
        format.json { render json: @teacher_cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher_cohorts/1
  # PATCH/PUT /teacher_cohorts/1.json
  def update
    respond_to do |format|
      if @teacher_cohort.update(teacher_cohort_params)
        format.html { redirect_to @teacher_cohort, notice: 'Teacher cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher_cohort }
      else
        format.html { render :edit }
        format.json { render json: @teacher_cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher_cohorts/1
  # DELETE /teacher_cohorts/1.json
  def destroy
    @teacher_cohort.destroy
    respond_to do |format|
      format.html { redirect_to teacher_cohorts_url, notice: 'Teacher cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher_cohort
      @teacher_cohort = TeacherCohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_cohort_params
      params.require(:teacher_cohort).permit(:Teacher_ID, :Cohort_ID)
    end
end

app/helpers/teacher_cohorts_helper.rb
module TeacherCohortsHelper
end

app/views/teacher_cohorts/_form.html.erb
<%= form_with(model: teacher_cohort, local: true) do |form| %>
  <% if teacher_cohort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher_cohort.errors.count, "error") %> prohibited this teacher_cohort from being saved:</h2>

      <ul>
      <% teacher_cohort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Teacher_ID %>
    <%= form.number_field :Teacher_ID %>
  </div>

  <div class="field">
    <%= form.label :Cohort_ID %>
    <%= form.number_field :Cohort_ID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teacher_cohorts/edit.html.erb
<h1>EDITING TEACHER COHORT</h1>

<%= render 'form', teacher_cohort: @teacher_cohort %>

<%= link_to 'Show', @teacher_cohort, class: 'btn btn-success btn-xs' %>
<%= link_to 'Back', teacher_cohorts_path, class: 'btn btn-info btn-xs' %>

app/views/teacher_cohorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TEACHERS COHORTS</h1>

<table class="table table-hover">
  <thead>
    <div class="row" style="border: 1px solid black;"></div>
    <tr>
      <th>Teacher id</th>
      <th>Cohort id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher_cohorts.each do |teacher_cohort| %>
      <tr>
        <td><%= teacher_cohort.Teacher_ID %></td>
        <td><%= teacher_cohort.Cohort_ID %></td>
        <td><%= link_to 'Show', teacher_cohort %></td>
        <td><%= link_to 'Edit', edit_teacher_cohort_path(teacher_cohort) %></td>
        <td><%= link_to 'Destroy', teacher_cohort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher Cohort', new_teacher_cohort_path, class: 'btn btn-success btn-xs'   %>

app/views/teacher_cohorts/new.html.erb
<h1>NEW TEACHER COHORT</h1>

<%= render 'form', teacher_cohort: @teacher_cohort %>

<%= link_to 'Back', teacher_cohorts_path, class: 'btn btn-info btn-xs'   %>

app/views/teacher_cohorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>TEACHER ID:</strong>
  <%= @teacher_cohort.Teacher_ID %>
</p>

<p>
  <strong>COHORT ID:</strong>
  <%= @teacher_cohort.Cohort_ID %>
</p>

<%= link_to 'Edit', edit_teacher_cohort_path(@teacher_cohort), class: 'btn btn-success btn-xs'  %> 
<%= link_to 'Back', teacher_cohorts_path, class: 'btn btn-info btn-xs'   %>