config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"
  resources :student_cohorts
  resources :teacher_cohorts
  resources :teachers_cohorts
  resources :teachers
  resources :students
  resources :cohorts
  resources :courses
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # @admins = Admins.find(params[:id])
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/student_cohort.rb
class StudentCohort < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # belongs_to :cohorts
end

app/models/teacher_cohort.rb
class TeacherCohort < ApplicationRecord
end

app/models/teachers_cohort.rb
class TeachersCohort < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:Username, :Password)
    end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = Cohort.all
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
  end

  # GET /cohorts/1/edit
  def edit
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        format.html { redirect_to @cohort, notice: 'Cohort was successfully created.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohort }
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params.require(:cohort).permit(:Name, :Start_Date, :End_Date, :Course_ID, :Student_ID)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Title, :Hours)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/student_cohorts_helper.rb
module StudentCohortsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_cohorts_helper.rb
module TeacherCohortsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Username %>
    <%= form.text_field :Username %>
  </div>

  <div class="field">
    <%= form.label :Password %>
    <%= form.text_field :Password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>EDITING ADMIN</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin, class: 'btn btn-success btn-xs'  %> 
<%= link_to 'Back', admins_path, class: 'btn btn-info btn-xs'  %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ADMINS</h1>

<table class="table table-hover">
  <thead>

      <div id="main-container" class="container-fluid">
        <div class="row" style="border: 1px solid black;">
          <div class="col-xs-3">
    <tr>
      <th>USERNAME</th>
      <th>PASSWORD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.Username %></td>
        <td><%= admin.Password %></td>
        <td><%= link_to 'Show', admin, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin), class: 'btn btn-warning btn-xs' %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
      <div class="col-xs-9">

      </div>
    </div>
    <%= link_to 'New Admin', new_admin_path, class: 'btn btn-success btn-xs'  %>
    <%= link_to 'New Teacher', new_teacher_path, class: 'btn btn-success btn-xs'  %>
    <%= link_to 'New Course', new_course_path, class: 'btn btn-success btn-xs'  %>
    <%= link_to 'New Student', new_student_path, class: 'btn btn-success btn-xs'  %> <br /> <br />
    <%= link_to 'New Cohort', new_cohort_path, class: 'btn btn-success btn-xs'%>
    <%= link_to 'New Course', new_course_path, class: 'btn btn-success btn-xs'  %>
    <%= link_to 'New Teacher Cohort', new_teacher_cohort_path, class: 'btn btn-success btn-xs'  %>
    <%= link_to 'New Student Cohort', new_student_cohort_path, class: 'btn btn-success btn-xs'  %>

  </div>

</body>

<br>

app/views/admins/new.html.erb
<h1>NEW ADMIN</h1>

<%= render 'form', admin: @admin, class: 'btn btn-success btn-xs'  %>

<%= link_to 'Back', admins_path, class: 'btn btn-info btn-xs'  %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>USERNAME:</strong>
  <%= @admin.Username %>
</p>

<p>
  <strong>PASSWORD:</strong>
  <%= @admin.Password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) , class: 'btn btn-warning btn-xs'  %> 
<%= link_to 'Back', admins_path , class: 'btn btn-info btn-xs'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JCSDSED</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-#334fff border-bottom box-shadow">
      <h1 class="my-0 mr-md-auto font-weight-normal"><a class="p-2 text-dark, btn btn-basic btn-xs" href="/"><strong>JACQUES COUSTEAU'S SCHOOL OF DEEP SEA EXPLORATORY DIVING</strong></a></h1>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark, btn btn-primary btn-xs" href="/admins">ADMINS</a>
        <a class="p-2 text-dark, btn btn-success btn-xs" href="/teachers">TEACHERS</a>
        <a class="p-2 text-dark, btn btn-info btn-xs" href="/students">STUDENTS</a>
        <a class="p-2 text-dark, btn btn-warning btn-xs" href="/cohorts">COHORTS</a>
        <a class="p-2 text-dark, btn btn-danger btn-xs" href="/courses">COURSES</a>
      </nav>
    </div>
  </head>

  <body style="background-color: #f5f5ef;">

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <!-- <h3>Jacques Cousteau's School of Deep Sea Exploratory Diving</h3> -->
        </div>
        <div class="col-xs-9">
          <br />
          <br />

          <%= yield %>
          <br />
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.htmlOG.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jcsdsed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="main-container" class="container" style="background-color: #d69f7e;">
      <div class="row">
        <div class="col-xs-3">
          <h3>Jacques Cousteau School of Deep Sea Exploratory Diving</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>