config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"
  resources :student_cohorts
  resources :teacher_cohorts
  resources :teachers_cohorts
  resources :teachers
  resources :students
  resources :cohorts
  resources :courses
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_cohort.rb
class StudentCohort < ApplicationRecord
end

app/controllers/student_cohorts_controller.rb
class StudentCohortsController < ApplicationController
  before_action :set_student_cohort, only: [:show, :edit, :update, :destroy]

  # GET /student_cohorts
  # GET /student_cohorts.json
  def index
    @student_cohorts = StudentCohort.all
  end

  # GET /student_cohorts/1
  # GET /student_cohorts/1.json
  def show
  end

  # GET /student_cohorts/new
  def new
    @student_cohort = StudentCohort.new
  end

  # GET /student_cohorts/1/edit
  def edit
  end

  # POST /student_cohorts
  # POST /student_cohorts.json
  def create
    @student_cohort = StudentCohort.new(student_cohort_params)

    respond_to do |format|
      if @student_cohort.save
        format.html { redirect_to @student_cohort, notice: 'Student cohort was successfully created.' }
        format.json { render :show, status: :created, location: @student_cohort }
      else
        format.html { render :new }
        format.json { render json: @student_cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_cohorts/1
  # PATCH/PUT /student_cohorts/1.json
  def update
    respond_to do |format|
      if @student_cohort.update(student_cohort_params)
        format.html { redirect_to @student_cohort, notice: 'Student cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_cohort }
      else
        format.html { render :edit }
        format.json { render json: @student_cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_cohorts/1
  # DELETE /student_cohorts/1.json
  def destroy
    @student_cohort.destroy
    respond_to do |format|
      format.html { redirect_to student_cohorts_url, notice: 'Student cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_cohort
      @student_cohort = StudentCohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_cohort_params
      params.require(:student_cohort).permit(:Student_ID, :Cohort_ID)
    end
end

app/helpers/student_cohorts_helper.rb
module StudentCohortsHelper
end

app/views/student_cohorts/_form.html.erb
<%= form_with(model: student_cohort, local: true) do |form| %>
  <% if student_cohort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_cohort.errors.count, "error") %> prohibited this student_cohort from being saved:</h2>

      <ul>
      <% student_cohort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Student_ID %>
    <%= form.number_field :Student_ID %>
  </div>

  <div class="field">
    <%= form.label :Cohort_ID %>
    <%= form.number_field :Cohort_ID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_cohorts/edit.html.erb
<h1>EDITING STUDENT COHORT</h1>

<%= render 'form', student_cohort: @student_cohort %>

<%= link_to 'Show', @student_cohort, class: 'btn btn-success btn-xs' %>
<%= link_to 'Back', student_cohorts_path, class: 'btn btn-info btn-xs' %>

app/views/student_cohorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>STUDENT COHORTS</h1>

<table class="table table-hover">
  <thead>
    <div class="row" style="border: 1px solid black;"></div>
    <tr>
      <th>STUDENTS ID</th>
      <th>COHORT ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_cohorts.each do |student_cohort| %>
      <tr>
        <td><%= student_cohort.Student_ID %></td>
        <td><%= student_cohort.Cohort_ID %></td>
        <td><%= link_to 'Show', student_cohort %></td>
        <td><%= link_to 'Edit', edit_student_cohort_path(student_cohort) %></td>
        <td><%= link_to 'Destroy', student_cohort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Cohort', new_student_cohort_path, class: 'btn btn-info btn-xs'   %>

app/views/student_cohorts/new.html.erb
<h1>NEW STUDENT COHORT</h1>

<%= render 'form', student_cohort: @student_cohort %>

<%= link_to 'Back', student_cohorts_path, class: 'btn btn-info btn-xs' %>

app/views/student_cohorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>STUDENT ID:</strong>
  <%= @student_cohort.Student_ID %>
</p>

<p>
  <strong>COHORT ID:</strong>
  <%= @student_cohort.Cohort_ID %>
</p>

<%= link_to 'Edit', edit_student_cohort_path(@student_cohort), class: 'btn btn-success btn-xs'   %> 
<%= link_to 'Back', student_cohorts_path, class: 'btn btn-info btn-xs'   %>