config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"
  resources :student_cohorts
  resources :teacher_cohorts
  resources :teachers_cohorts
  resources :teachers
  resources :students
  resources :cohorts
  resources :courses
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # belongs_to :cohorts
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:First_Name, :Last_Name, :Age, :Education, :Salary)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :First_Name %>
    <%= form.text_field :First_Name %>
  </div>

  <div class="field">
    <%= form.label :Last_Name %>
    <%= form.text_field :Last_Name %>
  </div>

  <div class="field">
    <%= form.label :Age %>
    <%= form.text_field :Age %>
  </div>

  <div class="field">
    <%= form.label :Education %>
    <%= form.text_field :Education %>
  </div>

  <div class="field">
    <%= form.label :Salary %>
    <%= form.text_field :Salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> 
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TEACHERS</h1>

<table class="table table-hover">
  <thead>
    <div class="row" style="border: 1px solid black;"></div>
    <tr>
      <th>FIRST NAME</th>
      <th>LAST NAME</th>
      <th>AGE</th>
      <th>EDUCATION</th>
      <th>SALARY</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.First_Name %></td>
        <td><%= teacher.Last_Name %></td>
        <td><%= teacher.Age %></td>
        <td><%= teacher.Education %></td>
        <td><%= teacher.Salary %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path, class: 'btn btn-success btn-xs'  %>

app/views/teachers/new.html.erb
<h1>NEW TEACHER</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path, class: 'btn btn-info btn-xs'   %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.Last_Name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.Age %>
</p>

<p>
  <strong>Education:</strong>
  <%= @teacher.Education %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @teacher.Salary %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> 
<%= link_to 'Back', teachers_path %>